require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'

target 'rntheodemo' do

  platform :ios, '13.4'

  config = use_native_modules! 
  
  use_react_native!(
    :path => config[:reactNativePath], 
    :hermes_enabled => false
  )

  target 'rntheodemoTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'rntheodemo-tvOS' do

  platform :tvos, '13.4'

  config = use_native_modules!
  
  # Hermes not yet available on tvOS
  use_react_native!(
    :path => config[:reactNativePath], 
    :hermes_enabled => false
  )

  target 'rntheodemo-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  react_native_post_install(installer)
end
